# Generated by Django 2.2 on 2020-10-24 11:46

import blog.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('cover', models.FileField(blank=True, null=True, upload_to='files/category_cover/', validators=[blog.models.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(upload_to='files/user_avatar/', validators=[blog.models.validate_file_extension])),
                ('description', models.CharField(max_length=512)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('cover', models.FileField(upload_to='files/article_cover/', validators=[blog.models.validate_file_extension])),
                ('content', ckeditor.fields.RichTextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='blog.UserProfile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
        ),
    ]
